export const statusOptions = ["Scheduled", "Live", "Played", "Postponed"];
export const stageOptions = [
  "Group Stage",
  "Round of 16",
  "Quarter-Finals",
  "Semi-Finals",
  "Final",
];

export const sportsOptions = [
  "Soccer",
  "Basketball",
  "American Football",
  "Baseball",
  "Cricket",
  "Rugby",
  "Volleyball",
  "Tennis",
  "Badminton",
  "Table Tennis",
  "Golf",
  "Swimming",
  "Athletics",
  "Boxing",
  "Wrestling",
  "Judo",
  "Karate",
  "Taekwondo",
  "Ice Hockey",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Rowing",
  "Cycling",
  "Gymnastics",
  "Weightlifting",
  "Archery",
  "Shooting",
  "Horse Riding",
  "Chess",
];
